name: open_meteo_api
description: The interface and models for Open Meteo API
version: 0.1.0+1
publish_to: none



environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
    json_annotation: ^4.1.0
    meta: ^1.7.0
    equatable: ^2.0.3
    freezed_annotation: ^0.14.3
    http: ^0.13.3
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
